port: 8080
title: dw-ring
desc: dw-ring webring server demonstration
copyright: All Rights Reserved
permalink: https://ring.konakona.moe
track: 
long: >-
      ## Welcome

      dw-ring (dw's webring) is a webring software I made in mid-2024 that fixed
      a lot of the issues from simpler frontend-based javascript scripts as it
      checks if websites are online before sending the user there among other
      cool features like automatic thumbnail generation.
websites:
  - name: KONAKONA.MOE
    slug: konakona
    url: https://konakona.moe
    desc: >-
      diogo's (“dw”) autistic outlet: *NIX and NT blog (soon™), self-hosting, photos
      and etc.
    button: https://konakona.moe/88x31/konakona.png
    favicon: https://konakona.moe/favicon.ico
    join: "2024"
