port: 8080
title: dw-ring
desc: dw-ring webring server demonstration
copyright: GPLv3
permalink: https://ring.konakona.moe
track: ""
long: >-
      ## Welcome

      dw-ring (dw's webring) is a webring software I made in mid-2024 that fixed
      a lot of the issues from simpler frontend-based javascript scripts as it
      checks if websites are online before sending the user there among other
      cool features like automatic thumbnail generation.
websites:
  - name: diogo's website
    slug: diogo
    url: https://konakona.moe
    desc: >-
      diogo's personal blog about self-hosting, photos and etc.
    button: https://konakona.moe/88x31/debian-powered.gif
    favicon: https://konakona.moe/favicon.ico
    join: "2024"
